name: 我是小菜鸡
title: 【bingo】
description: Jekflix is a template for Jekyll inspired by Netflix and made by Thiago Rossener.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
email: moyumia@outlook.com
disqus_username: disqus_username
show_hero: true
